-- How many distinct terms are in the sequence generated by a^b
-- for 2<=a<=100 and 2<=b<=100?

import Data.Set (Set, empty, insert, size)

main :: IO ()
main = do
  (print . size . powerSet) [2..100]

powerSet :: (Integral a) => [a] -> Set a
powerSet xs = foldr powers empty xs
  where powers x a = foldr (\y b -> insert (x^y) b) a xs
