-- How many distinct terms are in the sequence generated by a^b
-- for 2<=a<=100 and 2<=b<=100?

import Data.Set (empty, insert, size)
import Data.List (foldl')

main :: IO ()
main = print . size $ foldl' (flip insert) empty [x^y | x <- [2..100], y <- [2..100]]
